### ISSUE TITLE
Long queries handled incorrectly by bertpassage and pooled_bertpassage

### ISSUE THREAD

**Issue by andrewyates** [capreolus-ir/capreolus#105]
The input sequence can become greater than `maxseqlen` if `len(querytoks)` is greater. This causes us to pass inputs to BERT that are too large:

https://github.com/capreolus-ir/capreolus/blob/master/capreolus/extractor/bertpassage.py#L354
https://github.com/capreolus-ir/capreolus/blob/master/capreolus/extractor/pooled_bertpassage.py#L145

@crystina-z can we fix this as part of feature/autotokenizer? I think the most straightforward solution is to rely on hgf's code to prepare the input (eg `tokenizer(segA, segB)`) rather than constructing it ourselves.

**Comment by crystina-z** [comment]
yup I think the `tokenizer.encode` handles this. 

So i'll also ignore Config `pretrained` from the tokenizer path?
since we don't really need to cache different `qid2token` and `docid2passge` for different pretrained tokenizers now I think? they only stored the untokenized query and documents, which r same for each pretrianed model.

**Comment by crystina-z** [comment]
actually now the `qid2token` stored by Tokenizer is just a copy of the `benchmark.topic`... @andrewyates any suggestion on how could let Tokenizer directly access the benchmark so it can directly do `benchmark.topic[qid]` rather than load from its local copy? 

Right now we pass `topic` through `_build_vocab` ([here](https://github.com/capreolus-ir/capreolus/blob/master/capreolus/extractor/bertpassage.py#L295)), we can also pass it to `id2vec` as `**kwargs` ([here](https://github.com/capreolus-ir/capreolus/blob/master/capreolus/extractor/bertpassage.py#L330)), yet since `id2vec` will be invoked millions of times...I'm not sure if it's "elegant" enough to pass a variable which don't change at all to it everytime

**Comment by andrewyates** [comment]
right now it looks like the qids are tokenized, but this could instead be done on the fly like we do with documents?
`self.qid2toks = {qid: self.tokenizer.tokenize(topics[qid]) for qid in tqdm(qids, desc="querytoks")}`

I'm thinking this is the easiest way to deal with the `pretrained` stuff right now:
- Remove the tokenizer as an extractor dependency. It only makes sense to use one here (hgf's) and the only configurable option is `pretrained`, which cannot be configure independently of the reranker, so we can just instantiate the tokenizer ourselves inside the module
- Pass `pretrained` as a function argument to the extractor somewhere. Passing it to `preprocess` is the easiest place, I think? Alternatively, add a `pretrained` config option that is ignored from the path (while being careful not to break caching :))

More generally, I have a plan for rearranging the Reranker and RerankTask dependencies to simplify all this management. It will happen after ECIR though. Basically, I think the RerankTask should only call `reranker.fit()` and `reranker.query()` with all this trainer/extractor management happening inside the reranker. This will also make it easier to use rerankers independently of the rest of the Capreolus pipeline.

**Comment by andrewyates** [comment]
A related bug to fix: we check the length of the passage before word piece tokenization, I think?
See https://github.com/capreolus-ir/capreolus/blob/master/capreolus/extractor/bertpassage.py#L234

**Comment by crystina-z** [comment]
ah true, sure will fix it also
