### ISSUE TITLE
Error when running the colab notebook

### ISSUE THREAD

**Issue by Tooba-ts1700550** [capreolus-ir/capreolus#148]
I get the following error when running the second line in colab notebook:

`!capreolus rank.searcheval with benchmark.name=nf searcher.name=BM25 searcher.index.stemmer=porter searcher.b=0.8
`
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' (/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py)

Please help. This is after Capreolus installs successfully.

**Comment by andrewyates** [comment]
You should be able to fix this error by downgrading sqlalchemy after installing Capreolus: `pip install sqlalchemy==1.3.24`

The issue is that a new, incompatible sqlalchemy version was recently released. This is fixed in git, and we'll make a new pypi release soon that avoids the need for manually downgrading.

**Comment by Tooba-ts1700550** [comment]
thank you, your solution fixed the issue.
