### ISSUE TITLE
Incompatible pytorch and torchvision versions

### ISSUE THREAD

**Issue by Ji-Xin** [capreolus-ir/capreolus#6]
This happens when I install it from pip:
> ERROR: torchvision 0.5.0 has requirement torch==1.4.0, but you'll have torch 1.2.0 which is incompatible.

**Comment by andrewyates** [comment]
This is because other colab packages pulled in torchvision and some other packages that we don't use.
Do you get an error message afterwards?

**Comment by andrewyates** [comment]
Thanks for pointing this out, @Ji-Xin. All but one of these messages should be gone in the master branch now. The exception is the warning related to albumentations, which seems to be caused by colab's Python distribution since this isn't related to any of Capreolus' dependencies.

I don't think we will make a new pip release for this as the messages don't prevent the package from being installed. However, you can install directly from git in the meantime. All warnings will be gone if you install a newer version of albumentations as well:
```
!pip install -cython
!pip install albumentations==0.3.0
!pip install -e git+git://github.com/capreolus-ir/capreolus@master#egg=capreolus
```
